### ISSUE TITLE
SMTP plugin not working for WP multisite setups

### ISSUE THREAD

**Issue by y0va** [indiehosters/docker-wordpress#1]
Strangely the plugin works only for singlesite setups. On multisites these errors appear:
```
root@panda /data/domains/solawi.viper.ecobytes.net # docker-compose exec app bash
root@de97a850e4fa:/var/www/html# php -a
Interactive shell

php > mail ('yova@ecobytes.net','test postfix','testmail');
sh: 1: -t: not found

root@de97a850e4fa:/var/www/html# php -i | grep sendmail
sendmail_from => no value => no value
sendmail_path =>  -t -i  =>  -t -i 
Path to sendmail =>  -t -i 
root@de97a850e4fa:/var/www/html# find / -name php.ini
root@de97a850e4fa:/var/www/html# sendmail
bash: sendmail: command not found
```
After installing sendmail and setting it's path in an ini file in the php config dir:

```
php > mail ('yova@ecobytes.net','test mail','mail test');
Recipient names must be specified
```

A nice workaround is using this plugin:  
https://wordpress.org/plugins/global-smtp/advanced/

**Comment by almereyda** [comment]
@unteem Do you know if this issue could be reproduced, has been solved, or is addressed in any way?

If this is an unsuitable place for it, we can also refile it at https://lab.libreho.st/libre.sh/docker/wordpress/issues

Strange it didn't get imported when migrating the repositories.
