### ISSUE TITLE
Published Docker Image is not synced with here nor upstream

### ISSUE THREAD

**Issue by almereyda** [indiehosters/docker-wordpress#2]
The `indiehosters/wordpress` image is not up to date with the latest commit by @unteem.

Since this repository does not use tagged releases, and its binaries are not compiled on push, an update procedure of existing installations seems cumbersome. One would have to manually clone this repository, change the `image:` key to a `build:` key in associated Docker Compose files and would work from there.

**Comment by unteem** [comment]
yes it is a WIP, I'm slowly updating our dockerfiles and compose. Plan is actually to move everything on  lab.libreho.st.  Nothing is at synced in the libresh repositories at the moment. When everything will be updated and moved on libreho.st we will setup a docker registry there and get everything automated
